## Next Generation YAML Tools For Perl
# 
# YAML2 is a backwards compatible rewrite of YAML.pm. When YAML2 is done and
# stable, the code will be duplicated as YAML.pm, and YAML2 will be
# deprecated. At that point, you can simply `s/YAML2/YAML/g` in your code, and
# everything will work out.
# 
# YAML2 includes pure Perl code and Extensions of libyaml.
#
# NOTE: Currently this module does nothing useful, but is being uploaded to
# CPAN early and often to generate visibility and discussion.
#
# Copyright (c) 2007. Ingy döt Net <ingy@cpan.org>. All rights reserved.
#
# Licensed under the same terms as Perl itself.

package YAML2;
use 5.005003;
use YAML2::Base -base;
use strict;
use warnings;
our $VERSION = '0.01';

1;

## IDEAS:
#
# * Support JSON
# * Use all tests from YAML.pm and YAML::Syck
# * Support all options from YAML.pm and YAML::Syck
# * Use tests from pyyaml




























=for perldoc
This POD generated by Perldoc-0.22.
DO NOT EDIT. Your changes will be lost.

=encoding utf8

=head1 NAME

YAML2 - Next Generation YAML Tools For Perl

=head1 DESCRIPTION

YAML2 is a backwards compatible rewrite of YAML.pm. When YAML2 is done and
stable, the code will be duplicated as YAML.pm, and YAML2 will be
deprecated. At that point, you can simply C<s/YAML2/YAML/g> in your code, and
everything will work out.

YAML2 includes pure Perl code and Extensions of libyaml.

NOTE: Currently this module does nothing useful, but is being uploaded to
CPAN early and often to generate visibility and discussion.

=head1 AUTHOR

Ingy döt Net <ingy@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2007. Ingy döt Net. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut
